# Generated by Django 3.0.1 on 2019-12-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(max_length=100, unique=True, verbose_name='主机地址')),
                ('port', models.IntegerField(default=22, verbose_name='端口')),
                ('remark', models.CharField(max_length=255, verbose_name='描述')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
            ],
        ),
    ]
