# Generated by Django 3.0.1 on 2019-12-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='remark',
            field=models.CharField(max_length=255, unique=True, verbose_name='描述'),
        ),
    ]
