# Generated by Django 3.0.1 on 2019-12-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_hosts_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gorup_name', models.CharField(max_length=255, verbose_name='组名')),
            ],
        ),
        migrations.AlterField(
            model_name='hosts',
            name='group',
            field=models.IntegerField(verbose_name='组'),
        ),
    ]
