# Generated by Django 3.0.1 on 2019-12-25 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20191226_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('group_id', models.IntegerField(verbose_name='组ID')),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='gorup_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='组名'),
        ),
    ]
